#!/bin/bash

# https://werat.github.io/2017/02/04/tmux-ssh-agent-forwarding.html
if [ -z "$SSH_CLIENT" ] && [ ! -S ~/.ssh/ssh_auth_sock ] && [ -S "$SSH_AUTH_SOCK" ]; then
    ln -sf $SSH_AUTH_SOCK ~/.ssh/ssh_auth_sock
fi
