#!/usr/bin/env bash
set -eu -o pipefail

# https://werat.github.io/2017/02/04/tmux-ssh-agent-forwarding.html
if [ -n "${SSH_CLIENT-}" ] && [ -n "${SSH_AUTH_SOCK-}" ] && [ -S "${SSH_AUTH_SOCK}" ]; then
    ln -snf "$SSH_AUTH_SOCK" "$HOME/.ssh/ssh_auth_sock"
fi
