---
addons:
  apt:
    sources:
      - sourceline: ppa:jonathonf/vim
    packages:
      - tmux
      - vim
cache:
  directories:
    - "~/perl5"
    - "/usr/local"
dist: xenial
language: python
matrix:
  include:
    - os: linux
      python: 3.7
    - os: osx
      language: generic
before_script:
  - ln -sf $TRAVIS_BUILD_DIR ~/dot-files
script:
  - ./install.sh
