---
addons:
  apt:
    sources:
      - sourceline: ppa:jonathonf/vim
    packages:
      - tmux
      - vim
dist: xenial
language: python
matrix:
  include:
    - os: linux
      python: 3.7
    - os: osx
      language: generic
before_script:
  - ln -sf $TRAVIS_BUILD_DIR ~/dot-files
  - brew install homebrew/linuxbrew-core/eslint
  - brew install homebrew/linuxbrew-core/prettier
script:
  - ./install.sh
