---
services:
  app:
    image: ubuntu:24.04@sha256:186072bba1b2f436cbb91ef2567abca677337cfc786c86e107d25b7072feef0c
    platform: linux/arm64/v8
    volumes:
      - .:/root/dot-files
    working_dir: /root/dot-files
    command: /bin/env bash -c "./install.sh"
