" Load plugins using Pathogen. Don't worry if this bit doesn't make sense.

runtime bundle/vim-pathogen/autoload/pathogen.vim
" Bundle: tpope/vim-pathogen
call pathogen#infect()

" Bundle: https://github.com/altercation/vim-colors-solarized.git
" Bundle: https://github.com/scrooloose/nerdcommenter.git
" Bundle: https://github.com/bronson/vim-trailing-whitespace.git
" Bundle: https://github.com/scrooloose/nerdtree.git
" Bundle: https://github.com/wincent/Command-T.git
" Bundle: https://github.com/tpope/vim-fugitive.git
" Bundle: https://github.com/henrik/vim-indexed-search.git
" Bundle: https://github.com/Lokaltog/vim-powerline.git
" Bundle: https://github.com/tpope/vim-surround.git
" Bundle: https://github.com/vim-scripts/vim-json-bundle.git
" Bundle: https://github.com/bling/vim-airline.git

syntax enable
set background=dark
colorscheme solarized

set statusline=%F%m%r%h%w\ [FORMAT=%{&ff}]\ [TYPE=%Y]\ [ASCII=\%03.3b]\ [HEX=\%02.2B]\ [POS=%04l,%04v][%p%%]\ [LEN=%L]
set laststatus=2
set bs=2
filetype plugin on

au BufReadPost *.pl   set keywordprg=perldoc\ -f

" Indent using tabs (while in visual mode)
vnoremap < <gv
vnoremap > >gv
" make tab in v mode ident code
vmap <tab> >gv
vmap <s-tab> <gv
" make tab in normal mode ident code
nmap <tab> I<tab><esc>
nmap <s-tab> ^i<bs><esc>

" case insensitive search
set ignorecase smartcase

" highlight all matches
set hlsearch

" lookahead as search pattern is specified
set incsearch

" tabs
set softtabstop=4
set shiftwidth=4
set tabstop=4
set smarttab
set expandtab

" 4 space tabs in html get annoying
au BufRead,BufNewFile *.tmpl set filetype=html
autocmd FileType html :setlocal sw=2 ts=2 sts=2

" indents
set smartindent
set autoindent

" show matching brackets
autocmd FileType perl set showmatch

" show line numbers
autocmd FileType perl set number

let mapleader = ","


"command -range=% -nargs=* Tidy <line1>,<line2>!
"  \perltidy -pbp <args>

nnoremap <silent> = :%!perltidy -q<Enter>
vnoremap <silent> = :!perltidy -q<Enter>

"remove all trailing whitespace
:nnoremap <silent> - :let _s=@/<Bar>:%s/\s\+$//e<Bar>:let @/=_s<Bar>:nohl<CR>

"pretty print json
map <leader>jt <Esc>:%!json_xs -f json -t json-pretty<CR>

:set list!
:set listchars=tab:\|-

" enables shift-tab for outdent
exe 'set t_kB=' . nr2char(27) . '[Z'

" reflow text
nnoremap Q gqap
vnoremap Q gq

" highlight comments
highlight Comment term=bold ctermfg=white

"====[ Goto last location in non-empty files ]=======

autocmd BufReadPost *  if line("'\"") > 1 && line("'\"") <= line("$")
                   \|     exe "normal! g`\""
                   \|  endif

set stl=%f\ %m\ %r%{fugitive#statusline()}\ Line:%l/%L[%p%%]\ Col:%v\ Buf:#%n\ [%b][0x%B]
