requires 'fatfinger';
requires 'Git::Helpers';
requires 'GitHub::MergeVelocity';
requires 'HTTP::BrowserDetect';
requires 'LWP::ConsoleLogger';
requires 'Module::Version::Loaded';
requires 'Pithub';
requires 'WebService::SQLFormat';
requires 'WWW::Mechanize::Cached';
