---
name: Build

on:
  - pull_request
  - push

permissions:
  pull-requests: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    if: >
      ${{
      ( github.actor == 'dependabot[bot]' &&
        github.event_name == 'pull_request' ) ||
      ( github.actor != 'dependabot[bot]' &&
        github.event_name == 'push' )
      }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-24.04']

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '>=1.18.3'

      - name: Set up symlink to ~/dot-files
        run: cd && ln -s $GITHUB_WORKSPACE .

      - name: Install tmux deps
        run: sudo apt install libevent-dev

      - name: Install
        run: ./install.sh
        env:
          GITHUB_TOKEN: ${{ github.token }}
          PREFER_PKGS: 1
