name: Build

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v1
      - name: Set up symlink
        run: ln -s $ENV{GITHUB_WORKSPACE} $ENV{HOME}/dot-files
      - name: Run main installer
        run: ./install.sh
        env:
          CI: true
