name: Build

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v1
      - name: Set up symlink
        run: echo $GITHUB_WORKSPACE && cd && ln -s $GITHUB_WORKSPACE .
      - name: tree
        run: sudo apt-get install tree && tree ~/dot-files
      - name: Install symlinks
        run: ./installer/symlinks.sh
      - name: Install fpp
        run: ./installer/fpp.sh
      - name: Install Linux deps
        run: ./installer/linux.sh
      - name: Install yarn deps
        run: ./installer/yarn.sh
      - name: Configure Git
        run: ./configure/git.sh
      - name: Configure SSH
        run: ./configure/ssh.sh
      - name: Configure tmux
        run: ./configure/tmux.sh
      - name: Configure vim
        run: ./configure/vim.sh
        env:
          CI: true
