name: Build

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v1
      - name: apt-get update
        run: sudo apt-get update
      - name: Install Python setup tools
        run: sudo apt-get install python-setuptools python3-setuptools python3-venv
      - name: Set up symlink
        run: ln -s $GITHUB_WORKSPACE $HOME/dot-files
      - name: Run main installer
        run: ./install.sh
        env:
          CI: true
